// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoDawnxdcYXklylbw5beyHYiJQ6jRnUHE',
    appId: '1:618032539435:web:d7d00c8c23def0ab9c876e',
    messagingSenderId: '618032539435',
    projectId: 'mynotes-learn1',
    authDomain: 'mynotes-learn1.firebaseapp.com',
    storageBucket: 'mynotes-learn1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD3Hdla62ckcNCJEnIjoSkCyADvtWXvPc',
    appId: '1:618032539435:android:49f7b58f8471d83b9c876e',
    messagingSenderId: '618032539435',
    projectId: 'mynotes-learn1',
    storageBucket: 'mynotes-learn1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG0QNO1OiXv1j7F0kAvAgPuK2iukQ2hOU',
    appId: '1:618032539435:ios:52a7a746cb4bf7c79c876e',
    messagingSenderId: '618032539435',
    projectId: 'mynotes-learn1',
    storageBucket: 'mynotes-learn1.appspot.com',
    iosClientId: '618032539435-36k8vr52d3jojq5sp0i9el37b6bkl1mn.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotesLearn',
  );
}
